#!/bin/bash
./main  >testlog1.txt
echo "testing stage 1: init vdisk">>testlog1.txt
hexdump -C ../vdisk >> testlog1.txt
echo "As you can see, the vdisk has been initialized such that the first superblock (first 512 Byte addresses) are totally empty\n 
the next block is the free block vector, with the first 16 bits always set to 0, and the next 2 bits are also set to 0 because there are 2 blocks being used
for the root directory and the root directory's inode 

" >> testlog1.txt

echo "testing stage 2: create directory">> testlog1.txt
./main 1 >>testlog1.txt
hexdump -C ../vdisk>>testlog1.txt

echo "Now we created a directory which is stored in the datablock 16, with the inode in datablock 17

">>testlog1.txt
echo "testing stage 3: upload file">>testlog1.txt

./main 1 2 >>testlog1.txt
hexdump -C ../vdisk>>testlog1.txt
echo "now we have uploaded the smalltestfile from the current working directory.
this testfile occupies 3 blocks in memory, an the block addresses are visible in the inode  in address space /0x00002800

">>testlog1.txt


echo "testing stage 4: upload large file">>testlog1.txt
./main 1 2 3 >> testlog1.txt
hexdump -C ../vdisk>>testlog1.txt
echo "now we have uploaded a large file to the file system
the single indirection block is stored at address 0x4600, where the remaining data block addresses are clearly visible

That is the end of this test portion.
Please continue to the second folder in apps to download the files, remove them from vdisk, and delete the directories, exercising the capabilities of the PFS
">> testlog1.txt



